### ISSUE TITLE
Report typos

### ISSUE THREAD

**Issue by philip928lin** [IMMM-SFA/msd_uncertainty_ebook#115]
I am enjoying reading the UC eBook. I would like to report some typos to help improve the eBook:

1. **B.4.1 Tutorial: Sensitivity Analysis of the HYMOD Model:**
   - [p71] _The methods demonstrated in **"thistutorial"** can be applied to numerical models that simulate other complex non-linear systems._ => this tutorial
   - [p85] _In section 2.5, we saw how performing sensitivity analysis on different measurements of model output can **"yeild"** different results regarding the importance of each uncertain input. In this section, we’ll examine how performing this analysis over time can **"yeild"** additional insights into the performance of HYMOD._ => yield

2. [p136] _Deep uncertainty: Refers to situations where expert opinions consulted on a decision do not know or cannot agree on system boundaries, the outcomes of interest and their relative importance, or the prior probability **"Distribution"** for the various uncertain factors present._ => distribution

3. [p42] _Note: Put this into practice! Click the following badge to try out an interactive tutorial on utilizing Pre-Calibration and GLUE for HYMOD model calibration: Pre-Calibration Jupyter Notebook._ => I believe the current HYMOD does not have a demo for Pre-Calibration and GLUE.

4. [Suggestion] Move the **B.2 Sobol SA Tutorial** to the beginning of Appendix B, as other tutorials reference Sobol SA in their analysis.

**Comment by erexer** [comment]
Thanks for reporting those!
