### ISSUE TITLE
Usage of exploded acronym

### ISSUE THREAD

**Issue by crvernon** [IMMM-SFA/msd_uncertainty_ebook#19]
This subsection https://immm-sfa.github.io/msd_uncertainty_ebook/docs/html/3_sensitivity_analysis_the_basics.html#latin-hypercube-sampling-lhs uses the exploded `Latin hypercube sampling` several times after the initial designation `Latin hypercube sampling (LHS)`.  

Should this be the case?  Also, should it read all caps since it is an acronym (e.g., Latin Hypercube Sampling)?

**Comment by rg727** [comment]
If the acronym is defined once when it is first used, we should change all subsequent mentions to the acronym LHS. I believe that you only need Latin capitalized since it is a proper noun, but I've seen it written both ways. So I guess in that case, as long as we are consistent, we're ok!

**Comment by crvernon** [comment]
Thanks @rg727.  I will change to the LHS usage in that section.
