### ISSUE TITLE
Publication Feedback

### ISSUE THREAD

**Issue by ahamilton144** [IMMM-SFA/msd_uncertainty_ebook#29]
#### What did you enjoy about the eBook?

Great eBook! I found this to be very clear and informative. It will be a nice reference for collaborators and students.

#### Did you find a typo, inconsistency, or error?

I had one issue with the first Jupyter Notebook rendering in Binder, as well as some minor cosmetic comments:

- [x] 1. The first Jupyter notebook isn't working for me. When I try to run the first cell, I get a "BadZipFile" error when it tries to read in the MSD data.
- [x] 2. Personally I found the html landing page (https://immm-sfa.github.io/msd_uncertainty_ebook/docs/html/index.html) to be slightly unintuitive. I clicked on the first link, expecting that to take me to the beginning of the book, and only after a couple of minutes did I see the side bar and realize I was in chapter 2 and had missed preface & intro. I now see the helpful “Tip” about the sidebar at the bottom, so maybe this was just me being undercaffeinated, feel free to disregard.
- [ ] 3. Fig 1.1: Why are there more colors in the legend than appear in the figure?
- [ ] 4. 5.4.5: Should the second-order index be subsetted {i,j}? Or else if this is the sum of all second order effects for i, should there be a summation over j?
- [ ] 5. 3.4.3 discusses the correlation coefficient as a measure of sensitivity, and then 3.5 mentions R^2. Do you want to be consistent across the two, or are both commonly used?
- [x] 6. Fig. 4.3 caption: “reliable” spelled incorrectly
- [x] 7. A.7: Sentence starting with “In these cases, the likelihood…” is awkward – is there a missing “should be”?
- [x] 8. B.1.1.6: It’s not easy to tell the difference in robustness across the two policies by eye – maybe tell us the fraction of success in each to demonstrate the robust policy benefits?
- [x] 9. B.2.1: HTML version is not rendering the newlines in the list, which makes it hard to read compared to notebook in Binder. Also, looks like missing reference (Sobol3), and I might suggest adding brackets around the references to match the rest of the book and make it easier to read.
- [x] 10. B.2.1.6: Looks like x3 explains 2% of variance, not 1%
- [x] 11. B.2.1.7: “…identify important factors” should be “identifying”?

**Comment by ahamilton144** [comment]
Sorry, on point #4, that should say 3.4.5, not 5.4.5

**Comment by ahamilton144** [comment]
No problem! Actually at Rohini's request, I retried the Notebook and it worked fine. Earlier when it wasn't working, it also took a very long time to load the Binder, so not sure if there was some server issue or what. But seems to be working now.

**Comment by antonia-had** [comment]
Hi Andrew! Thank you for catching all those! Regarding your comment on the regression methods, it's a good point and one can use either, but I think the regression based methods using the standardized regression coefficient are more standard practice. They are related metrics, especially if the regression is only done on one factor (like the example cited that uses R^2)
