### ISSUE TITLE
Publication Feedback

### ISSUE THREAD

**Issue by jdossgollin** [IMMM-SFA/msd_uncertainty_ebook#38]
#### What did you enjoy about the eBook?

A great introductory textbook -- using it for my class

#### Did you find a typo, inconsistency, or error?

The HYMOD notebook doesn't run.
Specifically, in the first notebook the input data file doesn't load.

<img width="1821" alt="Screen Shot 2022-04-19 at 12 46 13 PM" src="https://user-images.githubusercontent.com/11929622/164064405-93405fff-bedf-4122-9268-1016f0389d4d.png">
il.]

```python
BadZipFile                                Traceback (most recent call last)
/tmp/ipykernel_61/2804211546.py in <module>
     10 
     11 # load example data
---> 12 msdbook.install_package_data()
     13 
     14 # load the Leaf River HYMOD input file

/srv/conda/envs/notebook/lib/python3.7/site-packages/msdbook/install_supplement.py in install_package_data()
     79     zen = InstallSupplement()
     80 
---> 81     zen.fetch_zenodo()

/srv/conda/envs/notebook/lib/python3.7/site-packages/msdbook/install_supplement.py in fetch_zenodo(self)
     45         r = requests.get(data_link)
     46 
---> 47         with zipfile.ZipFile(BytesIO(r.content)) as zipped:
     48 
     49             # extract each file in the zipped dir to the project

/srv/conda/envs/notebook/lib/python3.7/zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel)
   1256         try:
   1257             if mode == 'r':
-> 1258                 self._RealGetContents()
   1259             elif mode in ('w', 'x'):
   1260                 # set the modified flag so central directory gets written

/srv/conda/envs/notebook/lib/python3.7/zipfile.py in _RealGetContents(self)
   1323             raise BadZipFile("File is not a zip file")
   1324         if not endrec:
-> 1325             raise BadZipFile("File is not a zip file")
   1326         if self.debug > 1:
   1327             print(endrec)

BadZipFile: File is not a zip file
```

**Comment by crvernon** [comment]
Thanks @jdossgollin !  We will investigate this ASAP and get back to you with some info.

**Comment by crvernon** [comment]
@jdossgollin I assume you are running these locally and not on Binder, correct?

**Comment by crvernon** [comment]
Great thanks, I'll take a look

**Comment by jdossgollin** [comment]
Wow thanks! The URL I'm using is https://hub.gke2.mybinder.org/user/immm-sfa-msd_uncertainty_ebook-9chgx6kv/doc/tree/notebooks -- let me know if you need any other diagnostics.

Interestingly, I just re-ran and it worked.
Not sure what was going on but may not be worth much time on your end.

**Comment by jdossgollin** [comment]
Sorry about that. I can try running it a few more times to see if it was a one-off or a regular issue.

**Comment by crvernon** [comment]
@jdossgollin I believe this might have been a binder issue, but I am running a bunch of tests now to confirm.  I'll let you know ASAP what I find out.

**Comment by crvernon** [comment]
@jdossgollin after some further testing, it does seem to have been a binder issue.  I am able to open all of the notebooks from the ebook links and run them to completion.  

The issue you have raised is a good one because it shows inconsistency in the behavior of the ebook and an external service.  I believe we will move to change the backend of these notebooks from binder to an AWS instance of Linux running JupyterHub.  This should help with the preload of data and performance as well.  I'll keep this issue open until we get this setup.

Thanks for the valuable feedback!

**Comment by jdossgollin** [comment]
It's very cool that this book project has your support on the back end, and always happy to contribute to OSS in the limited ways I can

**Comment by crvernon** [comment]
Thanks @jdossgollin !

**Comment by crvernon** [comment]
Addressing in https://github.com/IMMM-SFA/msd_uncertainty_ebook/pull/45

**Comment by crvernon** [comment]
Hi @jdossgollin we now have the notebooks hosted on AWS and performance seems to be much better.  I'll close this now, but reach out anytime.  Thanks for your feedback!
